### ISSUE TITLE
No fracture notifications for manual fractures

### ISSUE THREAD

**Issue by paulipa** [skiedude/evestructures#18]
When we manually fracture the moons before the autofracture happens we do not seem to get a fracture notification on discord an the moon doesnt seem to get added to the fracture_notices table at all. Is there something wrong in our setup or is this a design for some reason?

**Comment by skiedude** [comment]
`if($diff_manual->days == 0 && $diff_manual->h <= 1 && $diff_manual->invert == 1 && !is_null($notification->extraction_webhook)) {
          if(is_null($fracture_notice) || $fracture_notice->notice == FALSE) {`

So this is the logic around Manual fracture notifications. There is nothing in the extraction API that says When a manual fracture was done. So my logic says

If the the time left before it fractures is equal to or less than 1 hour, and its not in the past already, then we make sure you have saved an extraction webhook, and that we haven't sent a notice already.

So have you done the following:
1. Extraction webhook is saved for the character who is providing that structure

**Comment by skiedude** [comment]
So the notification should come within an hour of when the chunk arrives and it could be manually fractured.

**Comment by skiedude** [comment]
Were you by chacne using slack webhooks?

**Comment by paulipa** [comment]
Aright thx. We are using discord hooks. But this clears things up, when we see the notification show up we know that we can then pop it instead of assuming notification to show up at autofracture instead.

**Comment by skiedude** [comment]
So were you getting notifications? just not when you were expecting them?

**Comment by paulipa** [comment]
Yeah we are getting notifications indeed but not just when we expected them ^^

**Comment by skiedude** [comment]
ah ok! yeah I really need to make a FAQ, the automatic fractures notifications will be clsoe to 3 hours after the arrival time
