### ISSUE TITLE
Login Button on Home Page does not use root URL

### ISSUE THREAD

**Issue by IvandaNothabeer** [skiedude/evestructures#2]
The Login Button on the Home page does not direct to the SSO login Page correctly.

To fix, Change resources/views/home.blade.php as follows .....

Line 171: `<a href="{{url('/sso/login')}}">`
Line 172: `<img src="{{ asset('/images')}}/small_black_login.png" alt="Login Button" class="pager center-block">`

Line 81: `<td align="right"><a href="{{url('/fetch')}}/{{$char->character_id}}"><button class="btn btn-default">Fetch</button></a>`

Line 126: `<td><a href="{{url('/home/structure')}}/{{$str->structure_id}}">{{$str->structure_name}}</a></td>`

(Thanks for releasing this btw. Looks Good.)

**Comment by skiedude** [comment]
By "does not redirect correctly" do you mean I just didn't build the <a> the correct way that Laravel offers? I was able to click the Eve Login image and add characters just fine.

**Comment by IvandaNothabeer** [comment]
Yes, it works fine if the root URL is the server. This is only an issue if you have a subdirectory, shared host. local dev environment etc.

**Comment by skiedude** [comment]
Ah! That makes more sense, I'll fix all the links this morning

**Comment by skiedude** [comment]
Updated. Should be good to go now if you git pull
